# Default values for mars.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global: {}

license:
  #file:
  overwrite: false

elasticsearch:
  clusterName: mars-elk
  replicas: 1

image:
  mars:
    repository: nocsysmars/mars
    pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
    tag: "accton"
  web:
    repository: nocsysmars/nginx
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.27.0-ares-accton"
  es:
    repository: nocsysmars/elasticsearch
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "7.9.0-oss"
  lgs:
    repository: nocsysmars/logstash
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "7.5.2-oss"

cmdstr:
  mars: |
    cp /tmp/collectd.conf /etc/collectd/
    echo "Hostname ${ONOS_IP}" >> /etc/collectd/collectd.conf

    service collectd restart
    service filebeat restart

    . /root/onos/provision.sh &
    /root/onos/bin/onos-service service
    #/root/onos/run_k8s.sh

  web: |
    service xinetd start
    service filebeat restart
    nginx -g "daemon off;"
    #/etc/nginx/update_mars_ip.sh

  #es: |
  #sleep 15
  #lgs: |
  #sleep 15

envs:
  lgs:
    jopts: "-Xmx2g -Xms2g"
  es:
    jopts: "-Xmx2g -Xms2g"
  mars:
    topo:  "clos"
    jopts: "-Xms8G -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode \
            -Dcom.sun.management.jmxremote -Dds.lock.timeout.milliseconds=10000"
    apps: >
      drivers
      com.accton.drivers.accton.gnmi
      com.accton.drivers.accton.rest
      com.accton.drivers.accton.snmp
      proxyarp
      restsb
      snmp
      org.onosproject.netconf
      org.onosproject.drivers.netconf
      org.onosproject.drivers.h3c.netconf
      linkdiscovery
      com.accton.provider.switchpolling
      com.accton.eventclient
      com.accton.useraccount
      com.accton.defaultcfg
      com.accton.alert
      com.accton.analyzer
      com.accton.utility
      com.accton.healthycheck
      com.accton.dhcpserver
      com.accton.dhcpv6server
      com.accton.endpoint
      com.accton.monitor
      com.accton.ntpserver
      com.accton.qos
      com.accton.sflow
      com.accton.storm-control
      com.accton.switchmgmt
      com.accton.topology
      com.accton.websocket
      com.accton.webssh

service:
  mars:
    type: ClusterIP
    mars:
      port: 8181
    webssh:
      port: 8443
  web:
    type: NodePort
    https:
      port: 443
      nodePort: 30443
    tftp:
      port: 69
      nodePort: 30069
    http:
      port: 80
      nodePort: 30080
  es:
    type: ClusterIP
    rest:
      port: 9200
    inter:
      port: 9300

  lgs:
    type: ClusterIP
    slogtcp:
      port: 5514
    slogudp:
      port: 5514
    beats:
      port: 5044
    collectd:
      port: 25826
    websocket:
      port: 3233


ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  mars:
    requests:
      memory: 8Gi
      cpu: 2000m
  lgs:
    requests:
      memory: 2Gi
      cpu: 1000m
  es:
    requests:
      memory: 2Gi
      cpu: 1000m
  web-ui:
    requests:
      memory: 1Gi
      cpu: 512m

  web-download:
    requests:
       memory: 500Mi
       cpu: 512m

pvc:
  web:
    swi:
      size: 1Gi
    download:
      size: 100Mi
  #mars:
  #  size: 4Gi
  es:
    size: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}

dev:
  enabled: false

