---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mars.fullname" . }}-nginx
  labels:
    {{- include "mars.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mars.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mars.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-web
          image: {{ include "mars.image" (list .Values.global.repoPrefix .Values.image.web.repository .Values.image.web.tag) }}
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}

          command:
            - /bin/sh
            - '-c'
            - |
              /bin/sh <<'EOF'
              {{ tpl (.Values.cmdstr.web) . | nindent 14 }}
              EOF

          ports:
            - containerPort: 443
            - containerPort: 69
            - containerPort: 80

---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: accton-mars
  name: mars-logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mars-logstash
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mars-logstash
    spec:
      containers:
      - name: logstash
        image: 'nocsysmars/logstash:7.5.2-oss'
        imagePullPolicy: IfNotPresent
        env:
        - name: LS_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: mars-configmap
              key: logstash_env_java_ops
        - name: ES_HOSTS
          value: "elasticsearch.accton-mars.svc.cluster.local:9200"
