---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mars.fullname" . }}-web-ui
  labels:
    {{- include "mars.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mars.selectorLabels" . | nindent 6 }}-web-ui
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mars.selectorLabels" . | nindent 8 }}-web-ui
    spec:
      automountServiceAccountToken: false
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60
      volumes:
        - name: volume-conf
          configMap:
            name: {{ .Release.Name }}-cm-cfg
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: fbweb.yml
                path: filebeat.yml
      containers:
        - name: {{ .Chart.Name }}-web-ui
          image: {{ include "mars.image" (list
                    .Values.global.repoPrefix .Values.image.web.repository .Values.image.web.tag) }}
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}

          {{- with .Values.resources.web }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: volume-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: volume-conf
              mountPath: /etc/filebeat/filebeat.yml
              subPath: filebeat.yml

          command:
            - /bin/sh
            - '-c'
            - |
              /bin/sh <<'EOF'
              {{ tpl (.Values.cmdstr.web) . | nindent 14 }}
              EOF

          ports:
            - containerPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mars.fullname" . }}-lgs
  labels:
    {{- include "mars.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mars.selectorLabels" . | nindent 6 }}-lgs
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mars.selectorLabels" . | nindent 8 }}-lgs
    spec:
      automountServiceAccountToken: false
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60

      containers:
        - name: {{ .Chart.Name }}-lgs
          image: {{ include "mars.image" (list
                    .Values.global.repoPrefix .Values.image.lgs.repository .Values.image.lgs.tag) }}
          imagePullPolicy: {{ .Values.image.lgs.pullPolicy }}

          {{- with .Values.resources.lgs }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          env:
            - name: LS_JAVA_OPTS
              value: "{{ .Values.envs.lgs.jopts }}"
            - name: ES_HOSTS
              value: "{{ printf "%s-es.%s:9200" (include "mars.fullname" .) .Release.Namespace }}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mars.fullname" . }}-mars
  labels:
    {{- include "mars.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mars.replicas }}
  selector:
    matchLabels:
      {{- include "mars.selectorLabels" . | nindent 6 }}-mars
  template:
    metadata:
#      {{- with .Values.podAnnotations }}
#      annotations:
#        {{- toYaml . | nindent 8 }}
#      {{- end }}

      {{- if .Values.mars.ipPool }}
      annotations:
        {{- (printf "cni.projectcalico.org/ipv4pools: '[ \"%s\" ]'" .Values.mars.ipPool) | nindent 8 }}
      {{- end }}

      labels:
        {{- include "mars.selectorLabels" . | nindent 8 }}-mars
    spec:
      automountServiceAccountToken: false
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60

      volumes:
        {{- if gt (int .Values.mars.replicas) 1 }}
        - name: config
          emptyDir: {}

        - name: init-scripts
          configMap:
            name: {{ .Release.Name }}-cm-init-sh
            defaultMode: {{ default 0744 .Values.mode }}
        {{- end }}

        - name: volume-conf
          configMap:
            name: {{ .Release.Name }}-cm-cfg
            items:
              - key: collectd.conf
                path: collectd.conf
              - key: fbmars.yml
                path: filebeat.yml
              - key: startup_netcfg.cfg
                path: startup_netcfg.cfg
        {{- if .Values.license.file }}
        - name: volume-lic
          secret:
            secretName: {{ .Release.Name }}-lic
            items:
              - key: license
                path: old.lic
        {{- end }}

      {{- if gt (int .Values.mars.replicas) 1 }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          image: tutum/dnsutils:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MARS_SVC
              value: {{ include "mars.fullname" . }}-mars-headless

            - name: ONOS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: MARS_CNT
              value: "{{ .Values.mars.replicas }}"

          command:
            - /bin/bash
            - '-c'
            - "/scripts/configure-cluster.sh > /config/cluster.json"

          volumeMounts:
            - name: config
              mountPath: /config

            - name: init-scripts
              mountPath: /scripts
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}-mars
          image: {{ include "mars.image" (list
                    .Values.global.repoPrefix .Values.image.mars.repository .Values.image.mars.tag) }}
          imagePullPolicy: {{ .Values.image.mars.pullPolicy }}

          volumeMounts:
            {{- if gt (int .Values.mars.replicas) 1 }}
            - name: config
              mountPath: /root/onos/config/cluster.json
              subPath: cluster.json
            {{- end }}

            - name: volume-conf
              mountPath: /tmp/collectd.conf
              subPath: collectd.conf
            - name: volume-conf
              mountPath: /etc/filebeat/filebeat.yml
              subPath: filebeat.yml
            {{- if .Values.license.file }}
            - name: volume-lic
              mountPath: /root/onos/download/old.lic
              subPath: old.lic
            {{- end }}
            - name: volume-conf
              mountPath: /root/onos/download/config/startup_netcfg.cfg
              subPath: startup_netcfg.cfg
          command:
            - /bin/sh
            - '-c'
            - |
              /bin/sh <<'EOF'
              {{- if .Values.license.file }}
                {{- if not .Values.license.overwrite }}
              [ ! -s /root/onos/download/license ] && \
                {{- end }}
              [ -s /root/onos/download/old.lic ] && \
              cp /root/onos/download/old.lic /root/onos/download/license
              {{- end }}
              {{ tpl (.Values.cmdstr.mars) . | nindent 14 }}
              EOF

          ports:
            - containerPort: 8101
            - containerPort: 8181
            - containerPort: 8443
          {{- with .Values.resources.mars }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          env:
            - name: ONOS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: WORK_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: ONOS_TOPOLOGY
              value: "{{ .Values.envs.mars.topo }}"
            - name: FABRIC_ADDRESS
              value: "unnumbered"
            - name: ES_DOC
              value: "_doc"
            - name: KARAF_DEBUG
              value: "true"
            - name: ES_HOSTS
              value: "{{ printf "%s-es.%s:9200" (include "mars.fullname" .) .Release.Namespace }}"
            - name: LOGSTASH_SERVICE_HOST
              value: "{{ include "mars.fullname" . }}-lgs.{{ .Release.Namespace }}"
            - name: JAVA_OPTS
              value: "{{ .Values.envs.mars.jopts }}"
            - name: ONOS_APPS
              value: "{{ .Values.envs.mars.apps }}"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - >-
                  curl --fail -u marsinneruser:onlycodeused -I
                  http://127.0.0.1:8181/mars/v1/network/configuration


