---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mars.fullname" . }}-web
  labels:
    {{- include "mars.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mars.selectorLabels" . | nindent 6 }}-web
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mars.selectorLabels" . | nindent 8 }}-web
    spec:
      volumes:
        - name: volume-conf
          configMap:
            name: {{ .Release.Name }}-cm-cfg
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: fbweb.yml
                path: filebeat.yml
      containers:
        - name: {{ .Chart.Name }}-web
          image: {{ include "mars.image" (list
                    .Values.global.repoPrefix .Values.image.web.repository .Values.image.web.tag) }}
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}

          {{- with .Values.resources.web }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: volume-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: volume-conf
              mountPath: /etc/filebeat/filebeat.yml
              subPath: filebeat.yml

          command:
            - /bin/sh
            - '-c'
            - |
              /bin/sh <<'EOF'
              {{ tpl (.Values.cmdstr.web) . | nindent 14 }}
              EOF

          ports:
            - containerPort: 443
            - containerPort: 69
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mars.fullname" . }}-lgs
  labels:
    {{- include "mars.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mars.selectorLabels" . | nindent 6 }}-lgs
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mars.selectorLabels" . | nindent 8 }}-lgs
    spec:
      containers:
        - name: {{ .Chart.Name }}-lgs
          image: {{ include "mars.image" (list 
                    .Values.global.repoPrefix .Values.image.lgs.repository .Values.image.lgs.tag) }}
          imagePullPolicy: {{ .Values.image.lgs.pullPolicy }}

          {{- with .Values.resources.lgs }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          env:
            - name: LS_JAVA_OPTS
              value: "{{ .Values.envs.lgs.jopts }}"
            - name: ES_HOSTS
              value: "{{ printf "%s-es.%s:9200" (include "mars.fullname" .) .Release.Namespace }}"

