{{- if .Values.license.file }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-lic
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  license:
  {{ .Values.license.file | b64enc | indent 4 }}
{{- end -}}

