---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mars.fullname" . }}-web-ui
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.web.type }}
  selector:
    {{- include "mars.selectorLabels" . | nindent 4 }}-web-ui
  ports:
    - port: {{ .Values.service.web.https.port }}
      nodePort: {{ .Values.service.web.https.nodePort }}
      name: https 

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mars.fullname" . }}-web-download
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.web.type }}
  selector:
    {{- include "mars.selectorLabels" . | nindent 4 }}-web-download
  ports:
    - port: {{ .Values.service.web.tftp.port }}
      name: tftp
      nodePort: {{ .Values.service.web.tftp.nodePort }}
    - port: {{ .Values.service.web.http.port }}
      name: dowload
      nodePort: {{ .Values.service.web.http.nodePort }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mars.fullname" . }}-mars
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.mars.type }}
  selector:
    {{- include "mars.selectorLabels" . | nindent 4 }}-mars
  ports:
    - port: {{ .Values.service.mars.mars.port }}
      name: mars
    - port: {{ .Values.service.mars.webssh.port }}
      name: webssh

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mars.fullname" . }}-es
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.es.type }}
  selector:
    {{- include "mars.selectorLabels" . | nindent 4 }}-es
  ports:
    - name: rest 
      port: {{ .Values.service.es.rest.port }}
    - name: inter-node
      port: {{ .Values.service.es.inter.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mars.fullname" . }}-lgs
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.lgs.type }} 
  selector:
    {{- include "mars.selectorLabels" . | nindent 4 }}-lgs
  ports:
    - protocol: TCP 
      port: {{ .Values.service.lgs.slogtcp.port }}
      name: syslog-tcp
    - protocol: UDP 
      port: {{ .Values.service.lgs.slogudp.port }}
      name: syslog-udp 
    - protocol: TCP 
      port: {{ .Values.service.lgs.beats.port }}      
      name: beats  
    - protocol: UDP
      port: {{ .Values.service.lgs.collectd.port }}
      name: collectd
    - port: {{ .Values.service.lgs.websocket.port }}
      name: websocket

