#
# An example to form a cluster of mars controllers.
# Need to aplly ippool.yaml and ipreserv.yaml first.
# Only works for calico cni now.
#
mars:
  replicas: 3
  ipPool: "mars-ippool"

cmdstr:
  mars: |
    cp /tmp/collectd.conf /etc/collectd/
    echo "Hostname ${ONOS_IP}" >> /etc/collectd/collectd.conf

    service collectd restart
    service filebeat restart

    . /root/onos/provision.sh &
    /root/onos/bin/onos-service service &
    sleep infinity
    #/root/onos/run_k8s.sh

resources:
  # Use less resources to simplify cluster creatiotn.
  mars:
    requests:
      memory: 8Gi
      cpu: 1000m
  lgs:
    requests:
      memory: 2Gi
      cpu: 100m
  es:
    requests:
      memory: 2Gi
      cpu: 100m
  web-ui:
    requests:
      memory: 1Gi
      cpu: 512m

  web-download:
    requests:
       memory: 500Mi
       cpu: 512m

